hFig=figure(...                    
    'Color'             ,btnColor                 ,...
    'IntegerHandle'     ,'on'                    ,...
    'DoubleBuffer'      ,'on'                     ,...
    'DeleteFcn'         ,'do_plot=0; set(htoggle_plot,''backgroundcolor'',[~do_plot do_plot 0]); delete(hFig);',...
    'MenuBar'           ,'none'                   ,...
    'HandleVisibility'  ,'on'                     ,...
    'Name'              ,[' Control record plot: ' caller]  ,...
    'Tag'               ,caller  ,...
    'NumberTitle'       ,'off'                    ,...
    'Units'             ,'pixels'                 ,...
    'Position'          ,figPos                   ,...
    'UserData'          ,[]                       ,...
    'Colormap'          ,[]                       ,...
    'Pointer'           ,'arrow'                  ,...
    'Visible'           ,'off'                     ...
    );

clear hAxes;
for i=1:length(ai.Channel)
    % Create Data subplot.
    hAxes(i) = axes(...
        'Position'          , [0.0200 0.05+(i-1)/length(ai.Channel) 0.980 -0.05+1/length(ai.Channel)],...
        'Parent'            , hFig);
        %'XLim'              , [0 get(ai, 'SamplesPerTrigger')],...
        %'YLim'              , [-0.5 0.5]...
       
    hLine(i)=plot(0,0,'color', chans_col{i});
    legend(ai.Channel.ChannelName(i));
    if strcmp(ai.Channel.ChannelName(i),'Microphone')
        hold on;
        hTrig=plot(0,0,'color','r','linewidth',2);
        h_rep_fun=plot(0,0,'x','color','m','erasemode','xor');    
    end
    set(hAxes(i),'box','off');
    zoom on
end
%if length(chans)>1
    set(hAxes, 'HandleVisibility', 'on');
    %end
set(hFig,'Visible','on','HandleVisibility', 'on');
zoom on
