%%%%%%%%%%%%%%%%%% Get synopsis
 if ~(exist([savepath birdname])==7)
            mkdir(savepath,birdname);
        end
       
if exist([savepath birdname '/synopsis.mat'])==2
    load([savepath birdname '/synopsis.mat'])
else
    synopsis=input(['Synopsis for ' birdname ': '],'s');
    save([savepath birdname '/synopsis.mat'],'synopsis')
end

% Position the GUI in the middle of the screen
btnColor=get(0,'DefaultUIControlBackgroundColor');
screenUnits=get(0,'Units');
set(0,'Units','pixels');
screenSize=get(0,'ScreenSize');
set(0,'Units',screenUnits);
figWidth=screenSize(3); figHeight=screenSize(4)/2;
figPos=[(screenSize(3)-figWidth)/2 1         figWidth                    figHeight];
ctr_size=300;
figPos_ctr=[screenSize(3)-ctr_size screenSize(4)-ctr_size ctr_size ctr_size-20];
% Create the figure window.

% Create the control figure 
hFig_ctr=figure(...                    
    'Color'             ,btnColor                 ,...
    'IntegerHandle'     ,'on'                    ,...
    'DoubleBuffer'      ,'on'                     ,...
    'DeleteFcn'         ,'close_record_window',...
    'MenuBar'           ,'none'                   ,...
    'HandleVisibility'  ,'on'                     ,...
    'Name'              ,'Control: Record'  ,...
    'Tag'               ,'Control'  ,...
    'NumberTitle'       ,'off'                    ,...
    'Units'             ,'pixels'                 ,...
    'Position'          ,figPos_ctr                   ,...
    'UserData'          ,[]                       ,...
    'Colormap'          ,[]                       ,...
    'Pointer'           ,'arrow'                  ,...
    'Visible'           ,'off'                     ...
    );

hAxes_ctr = axes(...
    'Position'          , [0.0200 0.0200 0.98 0.98],...
    'Parent'            , hFig_ctr,...
    'XLim'              , [0 1]...
    );

%%%%%%%%%%%%%%%%% Plot the indicators
hPatch=patch([0 thr_amp thr_amp 0],[0 0 1 1],'k');
hold on;
hPatch2=patch([0 max_amp max_amp 0],[0 0 1 1],'k','facecolor','none','edgecolor','k','erasemode','xor');
axis([0 axis_amp 0 10]);
axis off;
hLine_ctr(1)=plot(on_amp*[1 1],[0 1],'r','linewidth',3,'erasemode','xor');
set(hAxes_ctr, 'XLim', [0 axis_amp]);
ind_el_height=4;
ind_el_offset=1.1;
nbits=daqhwinfo(ai,'bits')-1;
    xh=2;
for i=1:length(ai.Channel)
   patch(ind_el_height*[0 0 1 1],[i-1 i i i-1]/xh+ind_el_offset,'k','facecolor','none','edgecolor','k');
    hPatch_el(i)=patch(ind_el_height/nbits*[0 0 1 1],ind_el_offset+[i-0.9 i-.1 i-.1 i-.9]/xh,chans_col{i},'erasemode','xor');
    for j=1:nbits
    plot(j*ind_el_height/nbits*[1 1],[i-1 i]/xh+ind_el_offset,'k');
    end
end


%%%%%%%%%%%%%%% Create the pushbuttons
htoggle_start = uicontrol(...
    'Parent'          , hFig_ctr,...
    'Style'           , 'pushbutton',...
    'Units'           , 'normalized',...
    'Position'        , [0.02 0.86 0.2 0.12],...
    'Value'           , 1,...
    'backgroundcolor'  , [~state_ai state_ai 0],...
    'String'          , 'RUN',...
    'fontsize'        , 14,...
    'Callback'        , 'toggle_ai;');
htoggle_save = uicontrol(...
    'Parent'          , hFig_ctr,...
    'Style'           , 'pushbutton',...
    'Units'           , 'normalized',...
    'Position'        , [0.02 0.72 0.2 0.12],...
    'Value'           , 1,...
    'backgroundcolor'  , [~do_save do_save 0],...
    'String'          , 'SAVE',...
    'fontsize'        , 14,...
    'Callback'        , 'toggle_save;');
htoggle_record = uicontrol(...
    'Parent'          , hFig_ctr,...
    'Style'           , 'pushbutton',...
    'Units'           , 'normalized',...
    'Position'        , [0.02 0.44 0.2 0.12],...
    'Value'           , 1,...
    'backgroundcolor'  , [~do_record do_record 0],...
    'String'          , 'REC',...
    'fontsize'        , 14,...
    'Callback'        , 'toggle_rec;');
htoggle_plot = uicontrol(...
    'Parent'          , hFig_ctr,...
    'Style'           , 'pushbutton',...
    'Units'           , 'normalized',...
    'Position'        , [0.02 0.58 0.2 0.12],...
    'Value'           , 1,...
    'backgroundcolor'  , [~do_plot do_plot 0],...
    'String'          , 'PLOT',...
    'fontsize'        , 14,...
    'Callback'        , 'if state_ai==0;do_plot=~do_plot;set(htoggle_plot,''backgroundcolor'',[~do_plot do_plot 0]); if do_plot; control_record_figure_plot;else; delete(hFig); end; end;');

%%%%%%%%%%%%%%%%%%% create the other buttons etc
hBirdname=uicontrol('Parent',hFig_ctr,'Style','text','String',birdname,...
    'units','normalized','position',[0.25 0.86 0.25 0.1],'FontSize',14,...
    'HorizontalAlignment','left');
hDirected=uicontrol('Parent',hFig_ctr,'Style','radiobutton','String','Directed',...
    'units','normalized','position',[0.55 0.7 0.3 0.065],'fontsize',14,...
    'buttondownfcn','',...
    'callback','if ~state_ai & ~directed; directed=~directed;directed_vs_undirected;end;',...
    'Value',directed);
hUndirected=uicontrol('Parent',hFig_ctr,'Style','radiobutton','String',...
    'Undirected','units','normalized','position',[0.55 0.78 0.4 0.065],...
    'fontsize',14,'callback','if ~state_ai & directed; directed=~directed;directed_vs_undirected;end',...
    'buttondownfcn','',...
    'Value',~directed,'HandleVisibility','off');
hFilecount=uicontrol('Parent',hFig_ctr,'Style','edit','String','',...
    'units','normalized','position',[0.25 0.72 0.16 0.1],'FontSize',14,...
    'HorizontalAlignment','left','backgroundcolor',[1 1 1]);
directed_vs_undirected;
hDirectory=uicontrol('Parent',hFig_ctr,'Style','text','String',dirname,...
    'units','normalized','position',[0.55 0.86 0.34 0.1],'FontSize',14,...
    'HorizontalAlignment','left');
hSynopsis=uicontrol('Parent',hFig_ctr,'Style','text','String',synopsis,...
    'units','normalized','position',[0.02 0.36 0.98 0.06],'FontSize',11,...
    'HorizontalAlignment','left','backgroundcolor',0*[1 1 1],'foregroundcolor',1*[1 1 1]);
hPfeedback_supp=uicontrol('Parent',hFig_ctr,'Style','text','String','P(Feedback)',...
    'units','normalized','position',[0.45 0.56 0.54 0.1],'FontSize',14,...
    'HorizontalAlignment','left');
hPfeedback=uicontrol('Parent',hFig_ctr,'Style','edit','String',num2str(pfeedback,3),...
    'units','normalized','position',[0.25 0.58 0.14 0.1],'FontSize',14,...
    'HorizontalAlignment','left');
%  hmenu(1) = uimenu('Parent', hFig,'Label', 'File');
%  hmenu(2) = uimenu(hmenu(1),...
%      'Label', 'Close demoai_fft',...
%      'Callback', 'demoai_fft(''close'',gcbf)');
%  hmenu(3) = uimenu('Parent', hFig,...
%      'Label', 'Help');
%  hmenu(4) = uimenu(hmenu(3),...
%      'Label', 'Data Acquisition Toolbox',...
%      'Callback', 'helpwin(''daq'')');
%  hmenu(5) = uimenu(hmenu(3),...
%      'Label', 'demoai_fft',...
%      'Callback', 'helpwin(''demoai_fft'')');


%    handle_ctr.filename=hfilename;

set(hAxes_ctr, 'HandleVisibility', 'on');
set(hFig_ctr,'Visible','on','HandleVisibility', 'on');
zoom off
