function createReachabilityPlot(yvector1)
%CREATEFIGURE(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 11-Feb-2010 10:54:13

% Create figure
figure1 = figure('Name',...
    'Reachability Plot for 01-21 DataSet, Eps=2, MinPnts=8');

% Create axes
axes('Parent',figure1);
box('on');
hold('all');

% Create bar
bar(yvector1,'EdgeColor','flat');

% Create xlabel
xlabel('Ordered Point (n->length(DataSet))');

% Create ylabel
ylabel('Reachability (Eps'')');

% Create title
title('Reachability Plot for DataSet @ Eps=2, MinPnts=8');

