function [times,ISI] = PeakDetect(thresh,startT,endT)

fs = 10000; %in Hz

%Select file for loading
[FileName, FileLoc]=uigetfile('*.txt','Select Spike File:');

%  Auto-generated by MATLAB on 30-Jun-2010 16:59:52
DELIMITER = ',';
HEADERLINES = 1;

% Import the file
temp = importdata([FileLoc '\' FileName], DELIMITER, HEADERLINES);
data = temp.data;

plot(data);

samples = 1:length(data)-1;
Dur = length(data)/fs;

UpCross = find(data(samples)<thresh & data(samples+1)>thresh);
DownCross = find(data(samples)>thresh & data(samples+1)<thresh);

if length(UpCross)==length(DownCross)
    for i=1:length(UpCross)
        times(i) = mean(UpCross(i),DownCross(i));
    end
end

times = times/fs;

times = times(times>=startT & times<=endT);
ISI = diff(times);
end

