hFigA=figure(...                    
    'Color'             ,btnColor                 ,...
'IntegerHandle'     ,'on'                    ,...
    'DeleteFcn'         ,'do_plotA=0; set(htoggle_plotA,''backgroundcolor'',[~do_plotA do_plotA 0]);',...
    'MenuBar'           ,'figure'                   ,...
    'HandleVisibility'  ,'on'                     ,...
    'Name'              ,'Control analyze plot: '  ,...
    'Tag'               ,'Analyze Plot'  ,...
    'NumberTitle'       ,'off'                    ,...
    'Units'             ,'pixels'                 ,...
    'Position'          ,figPosA                   ,...
    'UserData'          ,[]                       ,...
    'Pointer'           ,'arrow'                  ,...
    'Visible'           ,'off'                     ...
    );
num_subfig=2;
for i=1:num_subfig
    % Create Data subplot.
    hAxesA(i) = axes(...
        'Position'          , [0.05500 0.065+(i-1)/num_subfig 0.980 -0.05+1/num_subfig],...
        'Parent'            , hFigA);
   colormap(hsv);

    set(hAxesA(i),'box','off');
    zoom on
end
if num_subfig>1
    set(hAxesA, 'HandleVisibility', 'on');
end
set(hFigA,'Visible','on','HandleVisibility', 'on');
zoom on
